(define (problem train-travel-problem)
  (:domain train-travel)
  (:objects location-1 location-2 location-3)
  (:init
    (at location-1)
    (connected location-1 location-2)
    (connected location-2 location-1)
    (connected location-2 location-3)
    (connected location-3 location-2)
  )
  (:goal (at location-3))
)
